#!/bin/sh /etc/rc.common
#port from MTK SDK, remove unused code.
#=============================================================================
# smp_affinity: 1 = CPU1, 2 = CPU2, 3 = CPU3, 4 = CPU4
# rps_cpus: wxyz = CPU3 CPU2 CPU1 CPU0 (ex:0xd = 0'b1101 = CPU1, CPU3, CPU4)
#=============================================================================

START=99

APCLI_RTDEV="0"
OPTIMIZED_FOR="wifi"
CONFIG_RALINK_MT7621="y"
GE1_IF="eth0"
GE2_IF="eth1"

#LIST=`cat /proc/interrupts | sed -n '1p'`
#NUM_OF_CPU=0; for i in $LIST; do NUM_OF_CPU=`expr $NUM_OF_CPU + 1`; done;
#PHY_POS=`expr $NUM_OF_CPU + 3` #physical irq # position in /proc/interrups may vary with the number of CPU up

start_smp(){

# smp_affinity
	echo 2 > /proc/irq/3/smp_affinity  #GMAC
	echo 8 > /proc/irq/4/smp_affinity  #PCIe0 5G
	echo 8 > /proc/irq/24/smp_affinity #PCIe1 2G

# wifi rps
	echo 1 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/rax0/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/ra1/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/rax1/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/ra2/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/rax2/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/apcli0/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/apclix0/queues/rx-0/rps_cpus

# ether rps
	echo 9 > /sys/class/net/$GE1_IF/queues/rx-0/rps_cpus
	echo 9 > /sys/class/net/$GE2_IF/queues/rx-0/rps_cpus
}

start() {
	start_smp
	return 0
}

restart() {
	return 0
}

stop() {
	return 0
}

reload() {
	return 0
}
